backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "Personaje"
    label: "Personaje"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields:
      - { label: "Personaje", name: "title", widget: "string" }
      - { label: "Descripcion", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date",  widget: "datetime" }
      - { label: "Etiquetas", name: "tags", widget: "list", default: "post" }
      - { label: "Imagen", name: "image",  widget: "image" }
      - { label: "Alternativa", name: "imageAlt",  widget: "string" }
      - { label: "Habilidades", name: "body",  widget: "markdown" }